### PR TITLE
Update nested_list.R

### PR DESCRIPTION
**Pull request by jcolomb**
add possibility to use headings instead of list element, it also add the possiblity to use ordered list

### CODE REVIEW

**Comment by jcolomb** [comment]
thanks for this, it saved me hours of trying things and inefficient loops...

**Comment by jcolomb** [comment]
now markdown generated text tested with html and pdf outputs

**Comment by jcolomb** [comment]
Oh, I just saw this function is also in scienceverse, should I open the PR there ?

**Comment by debruine** [comment]
Actually, the main version of this function is at https://github.com/debruine/faux/blob/master/R/nested_list.R now (since faux is on CRAN). Sorry for being messy. I might kill this project soon and scienceverse will use the faux one in the future.

**Comment by jcolomb** [comment]
The new version is a bit more cryptic to me, not sure I could change it to add the mentioned functionality ...

**Pull request closed without merging**
